### ISSUE TITLE
Домашнее задание

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/purchase#5]
@coursar , Ильназ, хоть убейте - не понимаю следующих вещей:
- "Итого:" не суммирует, а просто складывает значение. Не получается связать "Итого:" и "Добавить", чтобы сразу после помещения в таск-лист считалась цифра со второго импута;
- Не импортируется lib.js в тесты.

**Comment by coursar** [comment]
1. lib.js сейчас не будет импортироваться, т.к. работает с localStorage, а тесты про него не знают
1. см. #37a7382 (не забудьте сделать git pull)
