### ISSUE TITLE
iter

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/purchase#7]
@coursar подставил правленную Вами переменную цикла в textContent элемента. Подскажите, пожалуйста, как должен будет выглядеть синтаксис вызова этой переменной в указанном элементе? https://github.com/DamirZaripov16/purchase/blob/0dd21426b61c55d32c88f7a26278ca95b75623e8/src/app/purchase.js#L23

**Comment by coursar** [comment]
если findMax возвращает строку или число - то ок.

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, подскажите, пожалуйста, почему данная переменная не считает и не отображает в maxPurchaseEl.textContent максимальную покупку (имя)? 
https://github.com/DamirZaripov16/purchase/blob/4d3d26cac549a54e53849d0110a5ab3d870ec506/src/app/lib.js#L37-L48

**Comment by coursar** [comment]
Потому что вы никогда туда не кладёте элементы. У вас всегда `purchases` пустой. И поиск max-element'а нужно делать в PurchaseList
