### ISSUE TITLE
Опубликовать на GitHub Pages

### ISSUE THREAD

**Issue by coursar** [DamirZaripov16/purchase#9]

**Comment by DamirZaripov16** [comment]
@coursar TravisCI не пускает в GitHub Pages из-за отсутствия тестов. А тесты я сделать не могу, т.к. внутри LocalStorage- Вы сказали, что на него тесты объясните потом :(

**Comment by coursar** [comment]
Сделайте пока заглушку, один тест 1 + 1

**Comment by DamirZaripov16** [comment]
@coursar не совсем понял какую заглушку нужно сделать

**Comment by coursar** [comment]
Сделайте тест, который ничего не тестирует. По факту, Jest работает с localStorage.

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, сделал, как Вы и сказали, но TravisCI все равно говорит "failed to deploy"
https://github.com/DamirZaripov16/purchase/blob/f4ce384897fd838996e4f2201f0d5d6e4dd2c2ee/src/test/purchase.test.js#L1-L7

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, сделано
